Order: 5
Links:
    - Name: Standard Numeric Format Strings
      URL: https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings
    - Name: Standard Date and Time Format Strings
      URL: https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings