Order: 5
Links:
    - https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings
    - https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings