# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# Only generated when examples changes is fine for now, but better is to split the "make a build" and "generate the site" into two separate actions, and use an artifact or a cache or something to run it.
# This is fine for now, but LISTEN... it could be better.

name: Generate Site By Example

on:
  push:
    paths: 
      - "/examples/**"
      - "**.mustache"
  pull_request:
    paths: 
      - "examples/**"
      - "**.mustache"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -o ./bin
    - name: debug data! where am i?
      run: ls -a bin
    - name: Generate Site
      run: ./bin/CSharpByExample
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@v2
      with:
        path: 'build'
    - name: Deploy to Pages
      id: deployment
      uses: actions/deploy-pages@v3
